#!/bin/bash
# This is use to create reserve proxy 

cat > /etc/nginx/sites-available/library << END
server
{
    listen      443 ssl http2;
    server_name www.mysite.com;
    access_log  /var/log/nginx/lib_access.log;
    error_log   /var/log/nginx/lib_error.log;

    ssl_certificate           /etc/nginx/SSL/ssl.crt;
    ssl_certificate_key       /etc/nginx/SSL/ssl.key;
    ssl_verify_client off;
    ssl_prefer_server_ciphers on;
    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256';
#    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
#    add_header X-XSS-Protection "1; mode=block";
#    add_header Content-Security-Policy "frame-ancestors 'self'";
#    add_header Referrer-Policy "origin";
#    add_header Permissions-Policy "geolocation=(self)";

   location /
   {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_pass  https://10.0.1.101;
   }
}
END

cat > /etc/nginx/sites-available/lib2 << END
server
{
    listen      443 ssl http2;
    server_name ww2.mysite.com;
    access_log  /var/log/nginx/lib2_access.log;
    error_log   /var/log/nginx/lib2_error.log;

    ssl_certificate           /etc/nginx/SSL/ssl.crt;
    ssl_certificate_key       /etc/nginx/SSL/ssl.key;
    ssl_verify_client off;
    ssl_prefer_server_ciphers on;
    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256';
#    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
#    add_header X-XSS-Protection "1; mode=block";
#    add_header Content-Security-Policy "frame-ancestors 'self'";
#    add_header Referrer-Policy "origin";
#    add_header Permissions-Policy "geolocation=(self)";

   location /
   {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_pass  https://10.0.1.102;
   }
}
END




